grafana:
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
      - name: 'default'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards/default
  dashboards:
    default:
      # some-dashboard:
      #   json: |
      #     $RAW_JSON
      prometheus-stats:
        gnetId: 2
        revision: 2
        datasource: Prometheus
      loki-stack:
        gnetId: 14055
        revision: 5
        datasource: Prometheus
      kube-state-metrics:
        gnetId: 13332
        revision: 12
        datasource: Prometheus
      k8s-node-exporter:
        gnetId: 8171
        revision: 1
        datasource: Prometheus
