config:
  extraFiles:
    fluent-bit.yaml: |
      service:
        # Required for health checks
        http_server: on
      pipeline:
        inputs:
          - name: tail
            tag: kube.*
            path: /var/log/containers/*.log
            multiline.parser: docker, cri
            Skip_Long_Lines: On

        outputs:
          # - name: stdout
          #   match: "*"

          - name: loki
            match: "*"
            host: loki-stack.grafana
            port: 3100

args:
  - --workdir=/fluent-bit/etc
  - --config=/fluent-bit/etc/conf/fluent-bit.yaml
